### ISSUE TITLE
Firefox blocks .click() on <a> tags with target prop

### ISSUE THREAD

**Issue by m-krebs** [Dosx001/mouselessV2#6]
### Describe the bug
Whenever you press <Enter> on a <a> tag that has for example the target property "_blank", Firefox blocks the element.click() event.

I would consider submitting a PR as soon as I hvae time to fix this issue.

My approach would be to check if named target prop exists on element and if trigger the browser.tabs API to open a new tab

**Comment by Dosx001** [comment]
I have a site that uses `target="_blank"` and mouseless works fine. Can you give me an example of this behavior?

**Comment by m-krebs** [comment]
For example at [StackOverflow](https://stackoverflow.com) when the cookie banner appears, there is the anchor tag with "Cookie Policy" as content. 

![grafik](https://github.com/Dosx001/mouselessV2/assets/80811771/95b9c512-453b-4c88-b809-d6ee860f5569)

If I open the mouselessV2 overlay, type in the letters and just press <Enter> I get a Banner at the top of the page that states Firefox prevented the page from opening a Popup.

It may be because of my enabled setting of blocking Pop-Ups in Firefox

**Comment by Dosx001** [comment]
Everything is working fine on my end. 

When I enable `Block pop-up windows` on Firefox, I get this when clicking the Cookie Policy link with mouseless.

![image](https://github.com/Dosx001/mouselessV2/assets/62494922/34fbd10b-4d99-46ad-81fc-a3eeef88d96b)

You can focus on the `Options` button by pressing `Alt+o`.

**Comment by m-krebs** [comment]
Closing issue because mouseless shouldn't bypass user (browser) settings
